/**
 * Legal copy rendered NATIVELY inside the app (app/legal.tsx) — no external
 * link, no web view. Kept in sync with the server's /privacy and /terms pages
 * (server/src/routes.ts), which exist only for the App Store Connect
 * "Privacy Policy URL" field and the shared web report footer.
 */

export const SUPPORT_EMAIL = "VerdictAI2026@outlook.com";
export const LEGAL_UPDATED = "17 July 2026";

export interface LegalSection {
  heading?: string;
  body?: string;
  bullets?: string[];
}

export const PRIVACY: LegalSection[] = [
  {
    body: "Verdict is anonymous by design. We collect the minimum needed to run the service, and we never sell or share your data.",
  },
  {
    heading: "What we collect",
    bullets: [
      "The website URLs you ask us to audit, and the screenshots, text and measurements our crawler captures from those public sites — kept so you can revisit your reports.",
      "A random identifier created on your device the first time you open the app, so we can keep your audit history and credits without an account, email or name.",
      "Your subscription/credit status, processed by Apple and RevenueCat. We never see your card or payment details.",
      "If you turn on weekly monitoring, a push notification token so we can alert you when a monitored site's score changes.",
    ],
  },
  {
    heading: "What we don't do",
    bullets: [
      "We don't sell or share your data with third parties for their own purposes.",
      "No advertising, and no tracking across other apps or websites.",
      "We don't collect your name, email, contacts or location.",
    ],
  },
  {
    heading: "AI processing",
    body: "Screenshots and text extracted from the websites you audit are sent to an AI provider (Anthropic or Google) purely to generate your report. They are not used to identify you.",
  },
  {
    heading: "Deleting your data",
    body: 'Open Settings → "Delete my data" to permanently remove your audits, screenshots, credits and identifier from our servers, immediately.',
  },
  {
    heading: "Contact",
    body: SUPPORT_EMAIL,
  },
];

export const TERMS: LegalSection[] = [
  {
    heading: "The service",
    body: "Verdict audits publicly accessible websites you ask us to review and produces automated reports. Reports are opinions generated by software and AI — use your own judgment before acting on them.",
  },
  {
    heading: "Acceptable use",
    body: "Only audit websites you own or are permitted to review. Don't use Verdict to attack, scrape, or overload sites.",
  },
  {
    heading: "Credits & subscriptions",
    body: "Each audit uses one credit. Failed or blocked audits are refunded automatically. Verdict Pro renews automatically until cancelled in your Apple ID settings; payment is charged to your Apple account. Prices are shown in the app before you buy. Weekly monitoring re-scans do not use your credits.",
  },
  {
    heading: "No warranty",
    body: "The service is provided “as is”, without warranties of any kind. Scores can change between runs as websites and AI models change.",
  },
  {
    heading: "Liability",
    body: "To the maximum extent permitted by law, our liability is limited to the amount you paid in the last 12 months.",
  },
  {
    heading: "Contact",
    body: SUPPORT_EMAIL,
  },
];
